version: '3.9'
services:
  web:
    build: .
    container_name: ${CONTAINER_NAME:-my-flask-app}  # Use env var or default value
    ports:
      - "8090:8000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
