name: Run Linters

on:
  workflow_dispatch:
  workflow_call:
  push:
    tags:
      - 'v*'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # Define the Python versions check against
        python-version: [ "3.10", "3.11", "3.12", "3.13" ]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: |
          make setup
          make install

      - name: Run Tests with Coverage
        run: |
          make lint
        continue-on-error: false
