name: Publish to PyPI

on:
  workflow_dispatch: # Enable manual runs
  push:
    tags:
      - 'v*' # Trigger on version tags

jobs:

  # Run tests before publishing
  call_tests:
    uses: ./.github/workflows/tests.yml

  publish_to_pypi:
    runs-on: ubuntu-latest
    needs: call_tests

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Poetry
        run: |
          make setup

      - name: Install Python Dependencies
        run: |
          make install

      - name: Build and Publish Package
        run: |
          PYPI_TOKEN=${{ secrets.PYPI_API_TOKEN }} make publish # Need `PYPI_API_TOKEN` secret
